apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tlnguyen-com-demo.fullname" . }}
  labels:
    {{- include "tlnguyen-com-demo.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tlnguyen-com-demo.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
